INSERT INTO tickets (title, description, status, priority, requester_name, requester_email, assigned_to, created_at, updated_at)
VALUES
('Falha no login do painel', 'O utilizador nao consegue aceder ao painel administrativo apos redefinir a palavra-passe.', 'OPEN', 'HIGH', 'Vitor Silva', 'vitor@email.com', 'Ana Souza', CURRENT_TIMESTAMP, NULL),
('Timeout na pagina de faturacao', 'O cliente reportou timeout ao gerar a fatura mensal no sistema.', 'IN_PROGRESS', 'MEDIUM', 'Carlos Lima', 'carlos@email.com', 'Bruno Costa', CURRENT_TIMESTAMP, NULL),
('Email de recuperacao nao enviado', 'O sistema nao esta a enviar o email de recuperacao de palavra-passe para contas Outlook.', 'RESOLVED', 'HIGH', 'Marina Alves', 'marina@email.com', 'Fernanda Rocha', CURRENT_TIMESTAMP, NULL),
('Erro no upload da foto de perfil', 'O envio da imagem falha com erro de validacao mesmo quando o ficheiro PNG e valido.', 'OPEN', 'LOW', 'Joao Pedro', 'joao@email.com', NULL, CURRENT_TIMESTAMP, NULL),
('Indicadores do dashboard desatualizados', 'O dashboard de gestao apresenta valores antigos desde ontem.', 'CLOSED', 'MEDIUM', 'Patricia Gomes', 'patricia@email.com', 'Ana Souza', CURRENT_TIMESTAMP, NULL),
('Erro ao anexar comprovativo', 'O cliente nao consegue anexar o comprovativo de pagamento no formulario.', 'OPEN', 'MEDIUM', 'Lucas Martins', 'lucas@email.com', 'Bruno Costa', CURRENT_TIMESTAMP, NULL),
('Pesquisa de clientes lenta', 'A pesquisa de clientes demora mais de dez segundos para apresentar resultados.', 'IN_PROGRESS', 'HIGH', 'Bianca Rocha', 'bianca@email.com', 'Fernanda Rocha', CURRENT_TIMESTAMP, NULL),
('Notificacao duplicada por email', 'O sistema esta a enviar a mesma notificacao de forma duplicada.', 'RESOLVED', 'LOW', 'Ricardo Melo', 'ricardo@email.com', NULL, CURRENT_TIMESTAMP, NULL),
('Erro ao exportar relatorio', 'A exportacao do relatorio financeiro termina com erro interno.', 'OPEN', 'HIGH', 'Sofia Alves', 'sofia@email.com', 'Ana Souza', CURRENT_TIMESTAMP, NULL),
('Campo telefone sem validacao', 'O formulario de registo aceita numeros de telefone invalidos.', 'CLOSED', 'LOW', 'Diogo Fernandes', 'diogo@email.com', 'Bruno Costa', CURRENT_TIMESTAMP, NULL),
('Sessao expira demasiado cedo', 'Os utilizadores estao a ser desconectados apos poucos minutos de inatividade.', 'OPEN', 'MEDIUM', 'Andre Silva', 'andre@email.com', 'Fernanda Rocha', CURRENT_TIMESTAMP, NULL),
('Erro ao atualizar morada', 'A atualizacao da morada do cliente nao esta a ser persistida.', 'IN_PROGRESS', 'MEDIUM', 'Carla Mendes', 'carla@email.com', 'Ana Souza', CURRENT_TIMESTAMP, NULL),
('Botao guardar sem resposta', 'O botao guardar nao executa nenhuma acao na pagina de configuracoes.', 'OPEN', 'HIGH', 'Rita Costa', 'rita@email.com', NULL, CURRENT_TIMESTAMP, NULL),
('Tabela de pedidos desalinhada', 'A tabela de pedidos fica desalinhada em resolucoes menores.', 'RESOLVED', 'LOW', 'Miguel Santos', 'miguel@email.com', 'Bruno Costa', CURRENT_TIMESTAMP, NULL),
('Erro no calculo de desconto', 'O valor final da encomenda ignora o desconto promocional aplicado.', 'IN_PROGRESS', 'HIGH', 'Helena Sousa', 'helena@email.com', 'Fernanda Rocha', CURRENT_TIMESTAMP, NULL),
('Historico de atividades vazio', 'O historico de atividades nao mostra eventos recentes do utilizador.', 'OPEN', 'MEDIUM', 'Nuno Lopes', 'nuno@email.com', 'Ana Souza', CURRENT_TIMESTAMP, NULL),
('Permissao incorreta no modulo financeiro', 'Um utilizador sem perfil de gestor conseguiu aceder ao modulo financeiro.', 'OPEN', 'HIGH', 'Beatriz Oliveira', 'beatriz@email.com', 'Bruno Costa', CURRENT_TIMESTAMP, NULL),
('Erro ao cancelar subscricao', 'O cancelamento da subscricao falha ao confirmar a operacao.', 'CLOSED', 'MEDIUM', 'Tiago Ribeiro', 'tiago@email.com', NULL, CURRENT_TIMESTAMP, NULL),
('Dashboard com grafico incompleto', 'O grafico principal nao apresenta todos os meses do ano corrente.', 'RESOLVED', 'LOW', 'Marcos Pinto', 'marcos@email.com', 'Fernanda Rocha', CURRENT_TIMESTAMP, NULL),
('API externa indisponivel', 'A integracao com o servico externo de pagamentos esta intermitente.', 'IN_PROGRESS', 'HIGH', 'Daniela Castro', 'daniela@email.com', 'Ana Souza', CURRENT_TIMESTAMP, NULL),
('Lista de utilizadores sem ordenacao', 'A listagem de utilizadores muda de ordem a cada carregamento da pagina.', 'OPEN', 'LOW', 'Fabio Correia', 'fabio@email.com', NULL, CURRENT_TIMESTAMP, NULL),
('Erro ao reenviar convite', 'O reenvio do convite para novo utilizador devolve erro de servidor.', 'OPEN', 'MEDIUM', 'Catarina Leal', 'catarina@email.com', 'Bruno Costa', CURRENT_TIMESTAMP, NULL),
('Campos obrigatorios sem destaque', 'O formulario nao destaca visualmente os campos obrigatorios.', 'RESOLVED', 'LOW', 'Ines Moreira', 'ines@email.com', 'Fernanda Rocha', CURRENT_TIMESTAMP, NULL),
('Demora no carregamento inicial', 'A pagina inicial demora demasiado tempo a carregar apos o login.', 'IN_PROGRESS', 'MEDIUM', 'Goncalo Araujo', 'goncalo@email.com', 'Ana Souza', CURRENT_TIMESTAMP, NULL),
('Erro na troca de palavra-passe', 'A alteracao da palavra-passe falha mesmo com credenciais validas.', 'OPEN', 'HIGH', 'Marta Teixeira', 'marta@email.com', 'Bruno Costa', CURRENT_TIMESTAMP, NULL),
('Notificacao push nao recebida', 'Os utilizadores nao recebem notificacoes push em dispositivos Android.', 'RESOLVED', 'MEDIUM', 'Eduardo Pires', 'eduardo@email.com', NULL, CURRENT_TIMESTAMP, NULL),
('Filtro por data inconsistente', 'O filtro por data retorna resultados fora do intervalo selecionado.', 'OPEN', 'HIGH', 'Sara Monteiro', 'sara@email.com', 'Fernanda Rocha', CURRENT_TIMESTAMP, NULL),
('Erro ao gerar segunda via', 'A geracao de segunda via do documento falha para alguns clientes.', 'IN_PROGRESS', 'MEDIUM', 'Pedro Gomes', 'pedro@email.com', 'Ana Souza', CURRENT_TIMESTAMP, NULL),
('Mensagem de sucesso incorreta', 'O sistema mostra sucesso mesmo quando a operacao nao foi concluida.', 'CLOSED', 'LOW', 'Liliana Freitas', 'liliana@email.com', 'Bruno Costa', CURRENT_TIMESTAMP, NULL),
('Campos do perfil nao guardam', 'As alteracoes aos dados de perfil nao permanecem apos atualizar a pagina.', 'OPEN', 'MEDIUM', 'Afonso Barbosa', 'afonso@email.com', NULL, CURRENT_TIMESTAMP, NULL);
